Fixups
twilio/apkscale pull request #7
Opened 2021-03-06 02:59 UTC by paynerc

## Description

This PR fixes two things:

1. It appears after a release and the version bump that the CI badge always shows failed. I'm guessing it's because we skipped the last run and the badge doesn't like that?
2. Fixed the MavenCentral badge

## Breakdown

- Removed the `[skip ci]` in the patch bump task so that it still runs CI so the badge can report accurately.
- Fixed the MavenCentral badge link so it functions properly now.

## Validation

- 👀 

## Additional Notes

[Any additional comments, notes, or information relevant to reviewers.]

## Submission Checklist
 - [x] The source has been evaluated for semantic versioning changes and are reflected in `gradle.properties`
 - [x] The `CHANGELOG.md` reflects any **feature**, **bug fixes**, or **known issues** made in the source code

2021-03-06 15:45 UTC, Alton09 requested changes
Let's add the skip ci back into the bump patch command as the ci badge is still displaying failed for some reason even though the last ci job was a success. I'm able to see the correct maven central version in the badge so that looks good!

2021-03-07 00:38 UTC, paynerc commented
Does the badge look at the last job on all of the branches or the default branch only? If that is the case it won't show passing until there is a commit on the default branch that passes. I'm still thinking the skip ci is necessary on the version bump.

2021-03-07 00:40 UTC, paynerc commented
From the CircleCi docs, that's exactly what's happening:

> By default, a badge displays the status of a project’s default branch, though you can also display the status of specific branches.

2021-03-08 17:55 UTC, Alton09 approved these changes

2021-03-08 17:56 UTC, paynerc commented
CircleCI shows a failed badge if the last run job was skipped: https://discuss.circleci.com/t/status-badges-for-skipped-builds-show-as-failed/30182/11

2021-03-08 17:56 UTC, merged